name: flutter_sakura_base2
description: A Flutter project base by Sakura (https://github.com/sakura-sakai).

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # For Architecture
  flutter_hooks: ^0.18.2+1
  hooks_riverpod: ^1.0.3
  state_notifier: ^0.7.2+1

  # For Navigation
  auto_route: ^3.2.4

  # For Networking
  dio: ^4.0.4
  connectivity_plus: ^2.2.1

  # For Auth
  flutter_secure_storage: ^5.0.2

  # For Model
  equatable: ^2.0.3
  freezed_annotation: ^1.1.0

  # For env
  flutter_dotenv: ^5.0.2
  flutter_flavor: ^3.0.3

  # For widget_utils
  validators: ^3.0.0

  # For date time
  intl: ^0.17.0

  # For UIs
  device_preview: ^1.0.0
  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  flutter_svg: ^1.0.3
  video_player: ^2.2.19
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.7

  # For Analyzer
  flutter_lints: ^1.0.4

  # For Assets
  flutter_gen_runner: ^4.1.5

  # For Navigation
  auto_route_generator: ^3.2.3

  # For Model
  freezed: ^1.1.1

  # For Testing
  mocktail: any
  mocktail_image_network: any

flutter_gen:
  output: lib/widgets/elements/assets_gen/
  integrations:
    flutter_svg: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - .env/
    - assets/images/
    - assets/svgs/
    - assets/videos/

  fonts:
    - family: Rotunda
      fonts:
        - asset: assets/fonts/Rotunda-Bold.otf
          weight: 700
